# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'NavigationControllerExercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NavigationControllerExercise

pod 'Google-Mobile-Ads-SDK', '~> 7.0'

  target 'NavigationControllerExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NavigationControllerExerciseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
